
import type { Metadata } from "next";
import { Space_Grotesk, IBM_Plex_Sans_Arabic, Rubik, Nunito } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import {  hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '../../i18n/routing';
import { getMessages, setRequestLocale } from "next-intl/server";
import Script from "next/script";
import Providers from "@/shared/components/providers/providers";
import { ThemeProvider } from "@/shared/components/providers/ThemeProvider";
import { AppLoader } from "@/shared/components/providers/AppLoader";
import { Navbar } from "@/shared/components/layout/navbar/Navbar";
import { Footer } from "@/shared/components/layout/Footer";
import { AiCursor} from "@/shared/components/ui/AiCursor";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  variable: "--font-arabic",
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
})

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
})

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
})

export const metadata: Metadata = {
  title: "AI Mentor",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
 setRequestLocale(locale);
  const messages = await getMessages();

  const cookieStore = await cookies();
  const themeCookie = cookieStore.get("ai-mentor-theme");
  const theme = themeCookie?.value === "light" ? "light" : "dark";

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      className={`${theme} ${spaceGrotesk.variable} ${ibmPlexSansArabic.variable} ${rubik.variable} ${nunito.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <AppLoader displayTime={2000}>
          <Script id="theme-init" strategy="beforeInteractive">
            {`
              (function() {
                try {
                  var root = document.documentElement;
                  var stored = localStorage.getItem('ai-mentor-theme');
                  if (stored === 'light' || stored === 'dark') {
                    root.classList.remove('dark', 'light');
                    root.classList.add(stored);
                    root.style.colorScheme = stored;
                    document.cookie = 'ai-mentor-theme=' + encodeURIComponent(stored) + '; path=/; max-age=31536000; SameSite=Lax';
                  }
                } catch(e) {}
              })();
            `}
          </Script>
          <ThemeProvider>
            <Providers messages={messages} locale={locale}>
              <AiCursor />
              <Navbar />
              <main className="flex-1">
                {children}
              </main>
              <Footer />
            </Providers>
          </ThemeProvider>
        </AppLoader>
      </body>
    </html>
  );
}
