
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {  hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '../../i18n/routing';
import { getMessages, setRequestLocale } from "next-intl/server";
import Providers from "@/shared/components/providers/providers";
import { Navbar } from "@/shared/components/layout/navbar/Navbar";
import { Footer } from "@/shared/components/layout/Footer";
import { BlobCursor } from "@/shared/components/ui/BlobCursor";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],

});

export const metadata: Metadata = {
  title: "AI Mentor",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
 setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
          <Providers messages={messages} locale={locale}>
            <BlobCursor />
            <Navbar />
            <main className="flex-1">
              {children}
            </main>
            <Footer />
          </Providers>
      </body>
    </html>
  );
}
